# yaml-language-server: $schema=https://raw.githubusercontent.com/hadolint/hadolint/master/contrib/hadolint.json
---
ignored:
  - SC2086
  - DL3004
  - DL3002
  - DL3008
  - DL3016
  - DL3018
  - DL3003
trustedRegistries:
  - docker.io
  - ghcr.io
  - quay.io
